# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mixdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Initialized'), (1, 'Pending'), (2, 'Processing'), (3, 'Delivered'), (99, 'Seen')], db_index=True, default=1, null=True, verbose_name='Status')),
                ('remote_uri', models.URLField(null=True)),
            ],
        ),
    ]
