# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import mixdown.models
import uuid


class Migration(migrations.Migration):

    replaces = [('mixdown', '0001_initial'), ('mixdown', '0002_auto_20170524_1021'), ('mixdown', '0003_auto_20170524_1043'), ('mixdown', '0004_auto_20170524_1142'), ('mixdown', '0005_auto_20170524_1256'), ('mixdown', '0006_auto_20170524_1407'), ('mixdown', '0007_playlist_target_duration'), ('mixdown', '0008_auto_20170726_2114'), ('mixdown', '0009_remove_playlist_remote_absolute_url'), ('mixdown', '0010_auto_20170727_0757'), ('mixdown', '0011_auto_20170727_0802'), ('mixdown', '0012_playlist_task_id'), ('mixdown', '0013_auto_20170727_0855'), ('mixdown', '0014_auto_20170727_0912')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Initialized'), (1, 'Pending'), (2, 'Processing'), (3, 'Done'), (99, 'Error')], db_index=True, default=1, verbose_name='Status')),
                ('remote_uri', models.URLField(db_index=True, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('mixdown_file', models.FileField(blank=True, null=True, upload_to=mixdown.models.get_mixdown_upload_path)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('task_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
