# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mixdown', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixdown',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mixdown',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
