# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mixdown', '0004_auto_20170524_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='remote_absolute_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='remote_uri',
            field=models.URLField(db_index=True, null=True, unique=True),
        ),
    ]
