# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixdown', '0005_auto_20170524_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='mixdown_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Initialized'), (1, 'Pending'), (2, 'Processing'), (3, 'Done'), (99, 'Error')], db_index=True, default=1, verbose_name='Status'),
        ),
    ]
