# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixdown', '0006_auto_20170524_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='target_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
