# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixdown', '0008_auto_20170726_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='remote_absolute_url',
        ),
    ]
