# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixdown', '0010_auto_20170727_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
