# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mixdown', '0011_auto_20170727_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='task_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
