# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixdown', '0012_playlist_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='task_id',
            field=models.CharField(max_length=64),
        ),
    ]
