# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixdown', '0013_auto_20170727_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='task_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
